version: '2'
services:
  base:
    build: .
    volumes:
      - .:/app/
      - /app/node_modules
  web:
    extends:
      service: base
    command: npm start
    ports:
      - "3000:3000"
  test:
    extends:
      service: base
    command: npm test
